name: PR Diff Impact Evaluation

on:
  pull_request:
    branches: [main]

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Evaluate PR Diff
        id: eval
        uses: varsamlewis/eval-diff@latest
        with:
          typesafe_api_key: ${{ secrets.TYPESAFE_API_KEY }}
          format: "standard"
